require("gordon.lazy")
-- require("gordon.rocks")

require("gordon.config.lazy")
require("gordon.config.which-key")
require("gordon.config.remap")
require("gordon.config.set")
require("gordon.config.autocmd")

require("gordon.config.devicon")
require("gordon.config.file-tree")
require("gordon.config.telescope")
require("gordon.config.ai")
require("gordon.config.db")
require("gordon.config.cmp")
require("gordon.config.statusline")
require("gordon.config.git")
require("gordon.config.commander")
require("gordon.config.harpoon")
require("gordon.config.csv")
require("gordon.config.undotree")
require("gordon.config.snippet")
require("gordon.config.todo")
require("gordon.config.treesitter")
require("gordon.config.tmux")
require("gordon.config.zen")
require("gordon.config.test")
require("gordon.config.surround")
require("gordon.config.rest")
require("gordon.config.indent")
require("gordon.config.outline")
require("gordon.config.trouble")
require("gordon.config.colorizer")
require("gordon.config.base64")
require("gordon.config.tint")
require("gordon.config.lilypond")
require("gordon.config.colors")
-- require("gordon.config.split")
-- require("gordon.config.markview")
-- require("gordon.config.tailwind")

require("gordon.config.lsp")
