#!/bin/bash

red="#EC5F67"
yellow="#FAC863"
green="#99C794"

bat0=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0)
bat1=$(upower -i /org/freedesktop/UPower/devices/battery_BAT1)
state=$(echo "$bat0" | grep state | awk '{print $2}')
p0=$(echo "$bat0" | grep percentage | awk '{print $2}')
p1=$(echo "$bat1" | grep percentage | awk '{print $2}')

if [[ "${state}" == "charging" ]]; then
  icon="🔌"
else
  icon="📱"
fi
if [[ "${BLOCK_INSTANCE}" -eq 1 ]]; then
  icon=""
fi

echo ${icon} ${p0} ${p1}
echo ${icon} ${p0} ${p1}

# p0=${p0/\%/}
# p1=${p1/\%/}
# if [[ "$((p0+p1))" -lt 66 ]]; then
#   echo "$red"
# elif [[ "$((p0+p1))" -lt 132 ]]; then
#   echo "$yellow"
# else
#   echo "$green"
# fi
