#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 || "${BLOCK_BUTTON}" -eq 4 ]]; then
  xbacklight -inc 5
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 || "${BLOCK_BUTTON}" -eq 5 ]]; then
  xbacklight -dec 5
fi

brightness=$(xbacklight -get)
brightness=${brightness/.*/}

echo $brightness%
echo $brightness%
