#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 || "${BLOCK_BUTTON}" -eq 4 ]]; then
  amixer -q sset Master 5%+
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  amixer -q sset Master toggle
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 || "${BLOCK_BUTTON}" -eq 5 ]]; then
  amixer -q sset Master 5%-
fi

statusLine=$(amixer get Master | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk -F ' ' '{print $5}' | tr -d '[]%')

if [[ "${status}" == "on" ]]; then
  if [[ "${volume}" -eq 0 ]]; then
    echo "MUTE"
    echo "MUTE"
    echo "#ff0000"
  else
    if [[ "${volume}" -lt 33 ]]; then
      icon="🔈"
    elif [[ "${volume}" -lt 66 ]]; then
      icon="🔉"
    else
      icon="🔊"
    fi
    echo "${icon} ${volume}%"
    echo "${icon} ${volume}%"
  fi
else
  echo "MUTE"
  echo "MUTE"
  echo "#ff0000"
fi
