-- require("tint").setup({
--   tint = -45, -- Darken colors, use a positive value to brighten
--   saturation = 0.6, -- Saturation to preserve
--   highlight_ignore_patterns = { "WinSeparator", "Status.*", "NvimTree*" }, -- Highlight group patterns to ignore, see `string.find`
-- })
